[tool.ruff]

line-length = 88
indent-width = 4
exclude = ["resources", "project/ui", "venv"]

[tool.ruff.lint]
select = [
  "E",  # pycodestyle errors
  "W",  # pycodestyle warning
  "F",  # pyflakes
  "I",  # isort
  "N",  # pep8-naming
  "UP", # pyupgrade
  "B",  # bugbear
  "C4", # comprehensions
  "SIM",# simplify
  "TID",# tidy imports
]

[tool.ruff.format]
docstring-code-format = true
line-ending = "auto"
